# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34816b94818f1fb59cf12cf5a82b0f5606eca3a8be2e200b685e83b7ad0c286fbdbc48260ff260edd273461cb8cf9eeb42b2585640e311eb79b7a1c96c73db1d

test:
  secret_key_base: ecf1aab6bfdd83b6ab65f887841d294c991b500c8d2a58fcf6577f5f7f7680923110c3a030b12d585a82dcff0ffdd6b03e8dc1eaf77a344991ed904d16dc4fdd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
